### ISSUE TITLE
Update example and documentation to use with mobile devices

### ISSUE THREAD

**Issue by darioodiaz** [gitsummore/nile.js#31]
To use userMedia on mobile devices you must use https/ssl server so, the broadcaster file must be on https connection, update the example and add it to the documentation for user that want to use it on mobile devices.

**Comment by carterbryden** [comment]
Chrome in general now needs SSL for a number of the more advanced features like webrtc, not just mobile.

**Comment by kbbqiu** [comment]
@darioodiaz Will do. We haven't optimized for mobile yet due to [#26](https://github.com/gitsummore/nile.js/issues/26)

**Comment by darioodiaz** [comment]
Ok, I keep testing that to see if I can help on that issue :)
